#!/usr/bin/env node
'use strict';
/**
 * Asset registration — the drop-in step of the Google Flow pipeline.
 *
 * After Flow generates a media file, drop it into the gallery assets tree
 * using the convention (documented in google_flow/README.md):
 *
 *   stitch_desifit_ui_design/assets/<kind>/<scope>/<prompt>.<ext>
 *
 *   kind   image | video | audio | icon
 *   scope  a manifest screen slug (e.g. onboarding_1_5) or "shared"
 *   prompt the manifest prompt name (e.g. hero-thali)
 *   ext    image png|jpg|webp · video mp4|webm · audio mp3|m4a|wav|aac|ogg · icon svg
 *
 * Then run this script: it validates every file against asset_manifest.json,
 * records bytes + sha256 in assets/registry.json, and refuses orphans or
 * ambiguous duplicates. Re-run tools/build_asset_chips.js afterwards so the
 * gallery chips reflect the new files, and commit both.
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const MANIFEST = path.join(ROOT, 'stitch_desifit_ui_design', 'google_flow', 'asset_manifest.json');
const ASSETS = path.join(ROOT, 'stitch_desifit_ui_design', 'assets');
const REGISTRY = path.join(ASSETS, 'registry.json');

const EXT_FOR_KIND = {
  image: ['png', 'jpg', 'webp'],
  video: ['mp4', 'webm'],
  audio: ['mp3', 'm4a', 'wav', 'aac', 'ogg'],
  icon: ['svg'],
};

const errors = [];
function fail(msg) { errors.push(msg); }

const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));

// ── Expected-unit inventory (for progress reporting) ───────────────────────
const screenUnits = []; // {kind, scope, prompt}
for (const [slug, entry] of Object.entries(manifest.screens || {})) {
  for (const [kind, list] of Object.entries(entry.assets || {})) {
    for (const a of list) screenUnits.push({ kind, scope: slug, prompt: a.prompt });
  }
}
const sharedUnits = []; // {kind, group, prompt}
for (const [group, g] of Object.entries(manifest.shared || {})) {
  for (const a of g.prompts || []) sharedUnits.push({ kind: g.assetKind, group, prompt: a.prompt });
}

// ── Scan the assets tree ────────────────────────────────────────────────────
function walk(dir, out) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else if (e.isFile() && e.name !== 'registry.json') out.push(p);
  }
}
const found = [];
if (fs.existsSync(ASSETS)) walk(ASSETS, found);

// ── Validate + map each file to a manifest unit ─────────────────────────────
const entries = [];
const seenUnits = new Map();
for (const f of found) {
  const rel = path.relative(ASSETS, f).split(path.sep).join('/');
  const parts = rel.split('/');
  if (parts.length !== 3) { fail(`${rel}: expected <kind>/<scope>/<prompt>.<ext>`); continue; }
  const [kind, scope, file] = parts;
  const ext = path.extname(file).slice(1).toLowerCase();
  const prompt = file.slice(0, file.length - ext.length - 1);
  if (!EXT_FOR_KIND[kind]) { fail(`${rel}: unknown kind "${kind}"`); continue; }
  if (!EXT_FOR_KIND[kind].includes(ext)) {
    fail(`${rel}: .${ext} not allowed for kind "${kind}" (want ${EXT_FOR_KIND[kind].join('|')})`);
    continue;
  }
  let unit = null;
  if (scope === 'shared') {
    unit = sharedUnits.find((u) => u.kind === kind && u.prompt === prompt) || null;
    if (!unit) fail(`${rel}: no shared prompt "${prompt}" with assetKind "${kind}" in asset_manifest.json`);
  } else {
    const scr = manifest.screens[scope];
    if (!scr) { fail(`${rel}: unknown screen scope "${scope}"`); continue; }
    const hit = (scr.assets[kind] || []).find((a) => a.prompt === prompt);
    if (!hit) fail(`${rel}: screen "${scope}" has no ${kind} prompt "${prompt}"`);
    else unit = { kind, scope, prompt };
  }
  if (!unit) continue;
  const key = `${kind}/${scope}/${prompt}`;
  if (seenUnits.has(key)) { fail(`${rel}: duplicate asset for ${key} (already ${seenUnits.get(key)})`); continue; }
  seenUnits.set(key, rel);
  const buf = fs.readFileSync(f);
  if (buf.length === 0) { fail(`${rel}: file is empty`); continue; }
  entries.push({
    kind, scope, prompt,
    file: `stitch_desifit_ui_design/assets/${rel}`,
    bytes: buf.length,
    sha256: crypto.createHash('sha256').update(buf).digest('hex'),
    registered: new Date().toISOString().slice(0, 10),
  });
}

if (errors.length) {
  console.error(`✗ register_assets: ${errors.length} problem(s) — nothing written`);
  for (const e of errors) console.error('  - ' + e);
  process.exit(1);
}

fs.mkdirSync(ASSETS, { recursive: true });
entries.sort((a, b) => (a.scope + a.kind + a.prompt).localeCompare(b.scope + b.kind + b.prompt));
const registry = {
  version: 1,
  note: 'Generated by tools/register_assets.js — do not edit by hand.',
  files: entries,
};
const hadCrlf = fs.existsSync(REGISTRY) && fs.readFileSync(REGISTRY, 'utf8').includes('\r\n');
let out = JSON.stringify(registry, null, 2) + '\n';
if (hadCrlf) out = out.replace(/\n/g, '\r\n');
fs.writeFileSync(REGISTRY, out);

// ── Progress report ─────────────────────────────────────────────────────────
const totalUnits = screenUnits.length + sharedUnits.length;
const perKind = {};
for (const e of entries) perKind[e.kind] = (perKind[e.kind] || 0) + 1;
console.log(`✓ registry: ${entries.length}/${totalUnits} manifest units have real files` +
  (entries.length ? ` (${Object.entries(perKind).map(([k, n]) => `${k} ${n}`).join(', ')})` : ''));
if (entries.length < totalUnits) {
  console.log(`  ${totalUnits - entries.length} still pending generation (pending is legal; registered files are hash-enforced)`);
}
