// File generated by Antigravity AI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_declarations
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Edit the placeholder strings below with your Google Cloud / Firebase credentials.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlV0KIgUeJo4-N-oYbtlA23p_iSz7nWik',
    appId: '1:652471571975:web:a00ee0c40af69e6c9a3ca2',
    messagingSenderId: '652471571975',
    projectId: 'desifit-app',
    authDomain: 'desifit-app.firebaseapp.com',
    storageBucket: 'desifit-app.firebasestorage.app',
    measurementId: 'G-TNQC76B0XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwnU0Ch7WBERyxgPzCUNRC4Nc0BYbCFqU',
    appId: '1:652471571975:android:9cfcb40b144b3a3b9a3ca2',
    messagingSenderId: '652471571975',
    projectId: 'desifit-app',
    storageBucket: 'desifit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_h9GCxWDAxb0TqRejwnyf85MT4AdTYIU',
    appId: '1:652471571975:ios:4a3f5d85ab50d1e79a3ca2',
    messagingSenderId: '652471571975',
    projectId: 'desifit-app',
    storageBucket: 'desifit-app.firebasestorage.app',
    iosBundleId: 'com.desifit.app.desifit',
  );

}